server:
  port: 8080

spring:
  application:
    name: springedu2

# mysql 설정
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/edudb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
#    # url: jdbc:mysql://mysql-container:3306/edudb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
#    username: jdbctest
#    password: jdbctest

# oracle 설정
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: spring
#    password: 1234

    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: 1234

# postgresql 설정
#  datasource:
#   driver-class-name: org.postgresql.Driver
#   url: jdbc:postgresql://localhost:5432/edudb?stringtype=unspecified
#   username: jdbctest
#   password: jdbctest

  jpa:
    # database-platform: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.OracleDialect
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      #ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace